- name: install redis from repo
  ansible.builtin.dnf:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: present
    disable_gpg_check: true

#Enable Redis 6.2 from package streams.
- name: enable redis
  ansible.builtin.command:  dnf module enable redis:remi-6.2 -y
#Install Redis
- name: install redis
  ansible.builtin.dnf:
    name: redis
    state: present
# allow remote connections
- name: allow remote connections
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
# start and enable redis
- name: start and enable redis service
  ansible.builtin.service:
    name: redis
    state: restarted
    enabled: yes