- name: "Install {{component}}"
  # hosts:  "{{component}}" hosts is local host because its ansible pull configuration
  hosts: localhost
  connection: local
#  strategy: debug
  vars_files:
  - "variables-{{env}}.yaml"
  become: yes
  roles:
  - "{{component}}"