
- name: configure erlang
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: configure rabbitmq
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: install rabbit mq
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: present

- name: start and enable rabbitmq
  ansible.builtin.service:
    name: rabbitmq-server
    state: restarted
    enabled: yes

# - name: create rabbitmq user
#   ansible.builtin.command: "rabbitmqctl add_user {{rq_user}} {{rq_password}}"

# - name: set permissions
#   ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"

# lets use community module for rabbitmq
  community.rabbitmq.rabbitmq_user:
    user: "{{ lookup('aws_ssm', '/roboshop/dev/rabbitmq_user', region='us-east-1', decrypt=True) }}"
    password: "{{ lookup('aws_ssm', '/roboshop/dev/rabbitmq_password', region='us-east-1', decrypt=True) }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present