# calling role from common role this is done by 
# using import role  
- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: node js setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: mongodb setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-setup

- name: mongodb setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd

# only for deployment this will run with deployment tag
- name: deployment
  ansible.builtin.import_role:
    name: common
    tasks_from: deployment
