- name: install mysql client
  ansible.builtin.dnf:
    name: mysql
    state: present

# check data if loaded properly 48:00
- name: check cities schema exists or not
  ansible.builtin.command:  mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
  register: schema

- name: print schema output
  ansible.builtin.debug:
    msg: "schema output: {{schema}}"

- name: load cities data
#  ansible.builtin.shell: "mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}}  < /app/schema/shipping.sql"
  ansible.builtin.shell: "mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}}  < /app/db/master-data.sql"
  when: schema.stdout != "1"

- name: create shipping user data
  ansible.builtin.shell: "mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}}  < /app/db/app-user.sql"