- name: disable and enable nodejs module
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

- name: Install NodeJS
  ansible.builtin.dnf:
    name: nodejs
    state: present
# this is not needed as its running in pipeline now 
# - name: install dependencies
#   ansible.builtin.command:
#     chdir: /app
#     cmd: npm install