- name: Install python packages
  ansible.builtin.dnf:
    name: "{{item}}"
    state: present
  loop:
  - python36
  - gcc
  - python3-devel

- name: install dependencies
  ansible.builtin.command:
    chdir: /app
    cmd: pip3.6 install -r requirements.txt